/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --include-runtime false --strict-vars false` (hash: f6932a0b20d0e113b2024eb450d1f3ac)
interface __BaseEnv_Env {
	MEDIA: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	NEXT_PUBLIC_GOOGLE_CLIENT_ID: string;
	NEXT_PUBLIC_GOOGLE_CALENDAR_ID: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/server/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NEXT_PUBLIC_GOOGLE_CLIENT_ID" | "NEXT_PUBLIC_GOOGLE_CALENDAR_ID">> {}
}
