/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --include-runtime false --strict-vars false` (hash: 4a18c6f1bbecf23e5c8b9d00bdec7e09)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	ORBIT_AUTH_USERNAME: string;
	ORBIT_AUTH_PASSWORD_HASH: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/server/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ORBIT_AUTH_USERNAME" | "ORBIT_AUTH_PASSWORD_HASH">> {}
}
