/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --include-runtime false --strict-vars false` (hash: 9fd7a554672a9b6371af38a3d6c71e66)
interface __BaseEnv_Env {
	MEDIA: KVNamespace;
	DB: D1Database;
	ASSETS: Fetcher;
	ORBIT_AUTH_USERNAME: string;
	ORBIT_AUTH_PASSWORD_HASH: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ORBIT_AUTH_USERNAME" | "ORBIT_AUTH_PASSWORD_HASH">> {}
}
