const escape = (value: string) => value.replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character]!);

export function loginPage({ error = '', next = '/', status = 200, configured = true, retryAfter }: {
  error?: string; next?: string; status?: number; configured?: boolean; retryAfter?: number;
} = {}) {
  const nonce = crypto.randomUUID().replaceAll('-', '');
  return new Response(`<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#15131a"><meta name="robots" content="noindex,nofollow"><title>Giriş yap · Orbit</title><link rel="icon" href="/favicon.svg"><style nonce="${nonce}">
*{box-sizing:border-box}body{margin:0;min-height:100svh;display:grid;place-items:center;padding:32px 20px;background:#15131a;color:#f4f1f8;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;-webkit-font-smoothing:antialiased}main{width:min(100%,420px)}.brand{display:flex;align-items:center;gap:10px;margin-bottom:64px;font-size:19px;font-weight:650;letter-spacing:-.5px}.mark{display:grid;place-items:center;width:32px;height:32px;border:1px solid #6b5c8b;border-radius:11px;color:#c3b1ed}.mark svg{width:21px;height:21px}.eyebrow{font-size:10px;font-weight:650;letter-spacing:2px;color:#bca8e8;margin:0 0 14px}h1{font-size:34px;line-height:1.2;letter-spacing:-1.25px;font-weight:550;margin:0 0 14px}.intro{font-size:14px;line-height:1.7;color:#a6a0b1;margin:0 0 34px}label.field{display:block;font-size:12px;font-weight:550;margin:20px 0 9px;color:#ded8e7}input:not([type=checkbox]){display:block;min-width:0;width:100%;height:50px;padding:0 14px;border:1px solid #39333f;background:#211d28;border-radius:10px;color:#f7f3fc;font:inherit;font-size:15px;outline:none;transition:border-color .15s,box-shadow .15s}input:not([type=checkbox]):focus{border-color:#b9a1e4;box-shadow:0 0 0 3px #b9a1e41c}input::placeholder{color:#726a80}.password{position:relative}.password input{padding-right:72px}.reveal{position:absolute;right:5px;top:5px;height:40px;padding:0 10px;border:0;border-radius:6px;background:transparent;color:#b8adca;font:inherit;font-size:12px;cursor:pointer}.reveal:focus-visible,button:focus-visible{outline:2px solid #d4bfff;outline-offset:3px}.remember{display:flex;align-items:center;gap:10px;font-size:13px;margin:20px 0 5px;cursor:pointer;width:fit-content}.remember input{accent-color:#ba9fe8;width:17px;height:17px;margin:0}.hint{margin:0 0 26px 27px;color:#93899f;font-size:11px;line-height:1.6}.submit{width:100%;display:flex;align-items:center;justify-content:center;gap:10px;min-height:50px;border:0;border-radius:10px;background:#c2a8ef;color:#251938;font:inherit;font-size:14px;font-weight:650;cursor:pointer;transition:background .15s}.submit:hover{background:#d0b9f4}.submit:disabled{opacity:.6;cursor:wait}.submit svg{width:17px}.error{padding:12px 14px;border-radius:9px;border:1px solid #7b4149;background:#382229;color:#ffb7c3;font-size:13px;line-height:1.6;margin:20px 0}.footer{display:flex;align-items:center;gap:7px;color:#8d849a;font-size:11px;margin-top:30px}.footer svg{width:13px;height:13px;flex-shrink:0}@media(max-height:760px){.brand{margin-bottom:36px}}@media(max-width:440px){h1{font-size:30px}body{padding:28px 24px}.brand{margin-bottom:40px}}
</style></head><body><main><div class="brand"><span class="mark"><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><circle cx="12" cy="12" r="8" stroke="currentColor" stroke-width="1.5"/><circle cx="12" cy="12" r="3" fill="currentColor"/><circle cx="19" cy="7" r="2.5" fill="#15131a" stroke="currentColor" stroke-width="1.5"/></svg></span>Orbit</div><p class="eyebrow">KİŞİSEL ÇALIŞMA ALANIN</p><h1>Kaldığın yerden<br>devam et.</h1><p class="intro">Planların, notların ve hedeflerin seni bekliyor.<br>Devam etmek için giriş yap.</p>
${error ? `<div class="error" role="alert">${escape(error)}</div>` : ''}
${configured ? `<form method="post" action="/auth/login"><input type="hidden" name="next" value="${escape(next)}"><label class="field" for="username">Kullanıcı adı</label><input id="username" name="username" autocomplete="username" autocapitalize="none" spellcheck="false" required maxlength="64" placeholder="Kullanıcı adın" autofocus><label class="field" for="password">Parola</label><div class="password"><input id="password" type="password" name="password" autocomplete="current-password" required maxlength="256" placeholder="Parolan"><button class="reveal" type="button" aria-label="Parolayı göster" aria-pressed="false">Göster</button></div><label class="remember"><input type="checkbox" name="remember" value="1">Beni hatırla</label><p class="hint">Kendi cihazında seç; her seferinde giriş yapman gerekmesin.</p><button class="submit" type="submit">Giriş yap<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 12h14m-5-5 5 5-5 5" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg></button></form>` : ''}
<p class="footer"><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><rect x="5" y="10" width="14" height="11" rx="3" stroke="currentColor" stroke-width="1.5"/><path d="M8 10V7a4 4 0 0 1 8 0v3" stroke="currentColor" stroke-width="1.5"/></svg>Bu alan yalnızca sana ait. Herkese açık kayıt yok.</p></main><script nonce="${nonce}">
// A signed-out browser must not retain private snapshots from older versions.
try{for(var i=localStorage.length-1;i>=0;i--){var key=localStorage.key(i);if(key&&key.startsWith('orbit'))localStorage.removeItem(key)}}catch(e){}
if('caches' in window)caches.keys().then(function(keys){return Promise.all(keys.filter(function(key){return key.startsWith('orbit-')}).map(function(key){return caches.delete(key)}))}).catch(function(){});
if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').then(function(registration){return registration.update()}).catch(function(){});
var reveal=document.querySelector('.reveal');if(reveal)reveal.addEventListener('click',function(){var input=document.getElementById('password');var show=input.type==='password';input.type=show?'text':'password';reveal.textContent=show?'Gizle':'Göster';reveal.setAttribute('aria-label',show?'Parolayı gizle':'Parolayı göster');reveal.setAttribute('aria-pressed',String(show))});var form=document.querySelector('form');if(form)form.addEventListener('submit',function(){var button=form.querySelector('.submit');button.disabled=true;button.textContent='Giriş yapılıyor…'});
// Revalidate after Back/Forward restores a previously signed-out page.
window.addEventListener('pageshow',function(event){if(event.persisted)location.reload()});
</script></body></html>`, { status, headers: {
    'Content-Type': 'text/html; charset=utf-8',
    'Cache-Control': 'private, no-store',
    'Content-Security-Policy': `default-src 'none'; style-src 'nonce-${nonce}'; script-src 'nonce-${nonce}'; img-src 'self'; connect-src 'self'; worker-src 'self'; form-action 'self'; base-uri 'none'; frame-ancestors 'none'`,
    ...(retryAfter ? { 'Retry-After': String(retryAfter) } : {}),
  } });
}
