export type DesignAxis = 'clarity' | 'expression' | 'trust' | 'density' | 'depth' | 'nostalgia' | 'play';
export type DesignStyle = {
  id: string; name: string; description: string; tags: string[]; useCases: string[];
  previewImages: { layout: 'interface' | 'composition'; label: string }[];
  colorCharacter: string; density: 'ferah' | 'dengeli' | 'yoğun';
  affinity: Record<DesignAxis, number>;
  tokens: { background: string; surface: string; ink: string; accent: string; secondary: string; radius: number; serif?: boolean; border?: number };
  principles: string[];
};
type Definition = Omit<DesignStyle, 'previewImages' | 'affinity'> & { affinity: number[] };
const define = (item: Definition): DesignStyle => ({ ...item,
  affinity: Object.fromEntries(['clarity','expression','trust','density','depth','nostalgia','play'].map((axis,index)=>[axis,item.affinity[index]])) as Record<DesignAxis,number>,
  previewImages: [{layout:'interface',label:'Ürün arayüzü'},{layout:'composition',label:'Görsel kompozisyon'}],
});
// A versioned, extensible catalogue of code-rendered SVG specimens, not stock photos.
export const designCatalog: DesignStyle[] = [
  define({id:'minimal',name:'Minimalism',description:'Az öğe, güçlü hiyerarşi. İçeriğin rahatça nefes aldığı bir yüzey.',tags:['Sade','Net'],useCases:['Üretkenlik','Notlar','Araçlar'],colorCharacter:'Nötr + tek vurgu',density:'ferah',affinity:[5,1,4,2,0,0,0],tokens:{background:'#f5f4f0',surface:'#ffffff',ink:'#25262a',accent:'#52694f',secondary:'#d6ddcf',radius:10},principles:['Her ekranda tek baskın aksiyon.','Renk yerine boşluk ve yazı ağırlığıyla hiyerarşi kur.']}),
  define({id:'tech-minimal',name:'Tech Minimal',description:'Keskin ölçüler, kontrollü renk ve teknik netlik.',tags:['Hassas','İşlevsel'],useCases:['Geliştirici araçları','Sistemler'],colorCharacter:'Grafit + elektrik mavisi',density:'dengeli',affinity:[5,2,5,4,1,0,0],tokens:{background:'#121a22',surface:'#1d2833',ink:'#e4eef6',accent:'#6bb5ff',secondary:'#3c556c',radius:4},principles:['Durumları metin ve simgeyle birlikte göster.','Monospace yazıyı yalnızca sayısal ve teknik ayrıntılarda kullan.']}),
  define({id:'dashboard',name:'Dashboard Pro',description:'Karşılaştırmayı ve günlük kararları kolaylaştıran düzen.',tags:['Analitik','Düzenli'],useCases:['Finans','Yönetim','Planlama'],colorCharacter:'Açık gri + mavi',density:'yoğun',affinity:[5,1,5,5,0,0,0],tokens:{background:'#edf1f7',surface:'#ffffff',ink:'#263451',accent:'#496fe8',secondary:'#cfdbf1',radius:8},principles:['İlk bakışta karar vermek için gereken bilgiyi öne çıkar.','Yoğun veride etiketleri ve hizalamayı tutarlı tut.']}),
  define({id:'bento',name:'Bento UI',description:'Farklı boyutlu ama ortak ritme sahip modüler bölümler.',tags:['Modüler','Esnek'],useCases:['Ürün tanıtımı','Çok işlevli araçlar'],colorCharacter:'Krem + lavanta',density:'dengeli',affinity:[4,3,4,4,2,0,2],tokens:{background:'#edeaf3',surface:'#faf9fd',ink:'#383344',accent:'#9c8bcb',secondary:'#d6d0e5',radius:18},principles:['Kart boyutu bilgi önemini anlatsın.','İlgisiz bilgileri sırf ızgarayı doldurmak için ekleme.']}),
  define({id:'soft-modern',name:'Soft Modern',description:'Sıcak nötrler ve yumuşak yüzeylerle sakin bir gündelik deneyim.',tags:['Yakın','Sakin'],useCases:['Kişisel araçlar','Topluluk'],colorCharacter:'Taş + adaçayı',density:'ferah',affinity:[5,2,4,2,2,0,2],tokens:{background:'#eeeee7',surface:'#f8f8f2',ink:'#41483d',accent:'#799779',secondary:'#d7dfce',radius:22},principles:['Gölgeyi yüzeyleri ayırmak için hafifçe kullan.','Sıcak tonu okunabilirlikten ödün vermeden kur.']}),
  define({id:'editorial',name:'Editorial / Swiss',description:'Büyük tipografi, güçlü ızgara ve belirgin bir anlatım sırası.',tags:['Tipografik','Kültürel'],useCases:['Portfolyo','Yayın','Showcase'],colorCharacter:'Kâğıt + kırmızı',density:'dengeli',affinity:[4,5,4,3,0,2,1],tokens:{background:'#f0ede5',surface:'#f6f3eb',ink:'#20201d',accent:'#db3e2e',secondary:'#d8d1c4',radius:0,serif:true},principles:['Başlık, görsel ve gövde metnini ortak bir ızgaraya bağla.','Her bölümde tek güçlü tipografik odak kullan.']}),
  define({id:'glass',name:'Glassmorphism',description:'Şeffaf katmanlar ve renkli arka planla hafif derinlik.',tags:['Katmanlı','Işıklı'],useCases:['Medya','Yaratıcı araçlar'],colorCharacter:'Mor + buz mavisi',density:'ferah',affinity:[2,4,2,1,5,0,3],tokens:{background:'#443b77',surface:'#8b8bb866',ink:'#ffffff',accent:'#9cdded',secondary:'#ca8acd',radius:18},principles:['Okunan metnin arkasında yeterince opak yüzey kullan.','Bulanıklığı büyük ve sınırlı bölgelerde tut.']}),
  define({id:'liquid',name:'Liquid Glass',description:'Akışkan, ışıkla değişen yüzeyler ve yumuşak kenarlar.',tags:['Akışkan','Duyusal'],useCases:['Immersive deneyim','Vitrin'],colorCharacter:'Okyanus + sedef',density:'ferah',affinity:[2,5,2,1,5,0,4],tokens:{background:'#173e53',surface:'#90ced855',ink:'#edffff',accent:'#a6eedc',secondary:'#96b8e5',radius:32},principles:['Hareketi yön ve geri bildirim için kullan.','Saydam kontrolün tıklama sınırını görünür tut.']}),
  define({id:'clay',name:'Claymorphism',description:'Dolgun şekiller, yumuşak hacim ve neşeli renkler.',tags:['Dokunsal','Neşeli'],useCases:['Oyunlaştırılmış araçlar','Yaratıcı ürünler'],colorCharacter:'Pastel mercan + mor',density:'ferah',affinity:[3,4,2,1,5,0,5],tokens:{background:'#f5e4df',surface:'#fff0e9',ink:'#60424f',accent:'#c39ce9',secondary:'#f0b09c',radius:28},principles:['Hacmi ana etkileşimlerde yoğunlaştır.','Dekoratif objeleri gerçek düğmelerden ayır.']}),
  define({id:'neumorphic',name:'Neumorphism',description:'Aynı renk yüzeyden yükselen veya içine gömülen kontroller.',tags:['Yumuşak','Dokunsal'],useCases:['Az kontrollü araçlar','Ses araçları'],colorCharacter:'Sis grisi',density:'ferah',affinity:[3,2,2,1,5,1,2],tokens:{background:'#dce2e5',surface:'#dce2e5',ink:'#405467',accent:'#6e92aa',secondary:'#b9c9d2',radius:18},principles:['Kontrolleri yalnızca gölgeyle tanımlama.','Odak ve seçili duruma görünür bir kenarlık ekle.']}),
  define({id:'skeuomorphic',name:'Skeuomorphism',description:'Fiziksel nesnelerin malzeme ve davranışını arayüze taşır.',tags:['Malzemeli','Tanıdık'],useCases:['Müzik','Nostaljik araçlar'],colorCharacter:'Deri + sıcak metal',density:'dengeli',affinity:[2,4,3,2,5,5,3],tokens:{background:'#493b32',surface:'#746454',ink:'#fff0d3',accent:'#d9ad6c',secondary:'#a18b70',radius:12,serif:true,border:2},principles:['Malzeme benzetmesini ürünün işleviyle ilişkilendir.','Görsel detayın küçük ekranda metni boğmasına izin verme.']}),
  define({id:'maximal',name:'Maximalism',description:'Çarpıcı renkler, büyük ölçekler ve kontrollü bir görsel yoğunluk.',tags:['Cesur','Katmanlı'],useCases:['Kampanya','Deneysel portfolyo'],colorCharacter:'Sarı + fuşya + kobalt',density:'yoğun',affinity:[1,5,1,3,3,2,5],tokens:{background:'#f1e533',surface:'#ffc8e9',ink:'#2d1780',accent:'#e546a0',secondary:'#6152e8',radius:3,border:2},principles:['Birçok öğe olsa da tek bir ana odak seç.','Gürültüyü kontrollü boşluklarla dengele.']}),
  define({id:'brutal',name:'Brutalism',description:'Ham kenarlar, görünür sınırlar ve doğrudan bir ifade.',tags:['Dürüst','Deneysel'],useCases:['Bağımsız ürünler','Cesur işler'],colorCharacter:'Siyah + sarı',density:'dengeli',affinity:[3,5,2,2,1,2,3],tokens:{background:'#eeeadd',surface:'#fffdf3',ink:'#161616',accent:'#f2db3f',secondary:'#c0b6f0',radius:0,border:4},principles:['Sert kenarları basit navigasyonla dengele.','Etkileşimleri açık metinlerle anlat.']}),
  define({id:'spatial',name:'Spatial UI',description:'Mekânda konumlanan paneller ve katmanlar arasında yön duygusu.',tags:['Mekânsal','Geleceksel'],useCases:['3D','Immersive sistemler'],colorCharacter:'Gece mavisi + ışık',density:'ferah',affinity:[2,4,3,2,5,0,3],tokens:{background:'#101d32',surface:'#344860',ink:'#e5f2ff',accent:'#7fd7ef',secondary:'#6268bc',radius:14},principles:['Derinliği bilgi ilişkisini anlatmak için kullan.','Hareketsiz ve iki boyutlu alternatifleri koru.']}),
  define({id:'bauhaus',name:'Bauhaus',description:'Temel geometriler, ana renkler ve işlevsel bir kompozisyon.',tags:['Geometrik','Grafik'],useCases:['Sanat','Eğitim','Kültür'],colorCharacter:'Kırmızı + mavi + sarı',density:'dengeli',affinity:[3,5,3,2,1,4,4],tokens:{background:'#ede5d6',surface:'#f8f0e2',ink:'#242525',accent:'#d94b35',secondary:'#315eb4',radius:0},principles:['Geometrinin bilgi gruplamasına katkısı olsun.','Ana renkleri eşit ağırlıkta kullanma.']}),
  define({id:'futuristic',name:'Futuristic Minimal',description:'Sessiz karanlık, ince ışık izleri ve hassas çizgiler.',tags:['Sinematik','Hassas'],useCases:['Teknoloji vitrini','Görsel deneyim'],colorCharacter:'Karbon + buz',density:'ferah',affinity:[4,4,4,2,3,0,1],tokens:{background:'#111718',surface:'#1e282a',ink:'#e7f2ef',accent:'#b6e3d4',secondary:'#4f7373',radius:3},principles:['Işığı yalnızca aktif veya önemli öğelerde kullan.','Dekoratif teknik veriler üretme.']}),
  define({id:'retro',name:'Retro Futuristic',description:'Geçmişin gelecek hayali: çizgiler, canlı renkler ve nostaljik ritim.',tags:['Nostaljik','Karakterli'],useCases:['Oyun','Müzik','Deneysel web'],colorCharacter:'Gece moru + neon',density:'dengeli',affinity:[2,5,2,2,3,5,4],tokens:{background:'#221c40',surface:'#49316a',ink:'#fff0d6',accent:'#f4ae61',secondary:'#e973c9',radius:5},principles:['Retro etkileri az sayıda belirgin motifte topla.','Gövde metnini dekoratif fontlardan uzak tut.']}),
  define({id:'luxury',name:'Dark Luxury',description:'Koyu yüzeyler, zarif tipografi ve ölçülü metalik vurgular.',tags:['Rafine','Sinematik'],useCases:['Premium ürün','Estetik vitrin'],colorCharacter:'Kömür + şampanya',density:'ferah',affinity:[4,4,5,1,2,2,0],tokens:{background:'#201e1d',surface:'#2c2925',ink:'#ede5d7',accent:'#cdb48b',secondary:'#706455',radius:2,serif:true},principles:['Az sayıdaki öğeye yüksek görsel özen göster.','Altın tonunu metin gövdesi yerine vurgu için kullan.']}),
  define({id:'playful',name:'Playful UI',description:'Canlı şekiller ve küçük sürprizlerle samimi bir dil.',tags:['Canlı','Arkadaşça'],useCases:['Oyun','Topluluk','Öğrenme'],colorCharacter:'Lavanta + mandalina',density:'dengeli',affinity:[3,4,2,2,3,1,5],tokens:{background:'#f1eafa',surface:'#fff8ee',ink:'#3e315a',accent:'#ef9a62',secondary:'#b9a3e4',radius:24},principles:['Küçük sürprizleri anlamlı geri bildirimlerde kullan.','Önemli kararları oyun gibi belirsiz bırakma.']}),
  define({id:'contrast',name:'High Contrast UI',description:'Kesin sınırlar ve güçlü kontrastla doğrudan erişim.',tags:['Okunaklı','Kararlı'],useCases:['Operasyon','Erişilebilir araçlar'],colorCharacter:'Siyah + beyaz + limon',density:'dengeli',affinity:[5,3,5,4,0,0,0],tokens:{background:'#121212',surface:'#262626',ink:'#ffffff',accent:'#e2f966',secondary:'#878787',radius:5,border:2},principles:['Kontrastı gerçek içerikte ölç; stil adı uygunluk garantisi değildir.','Durumu yalnızca renkle ifade etme.']}),
];
export const findDesignStyle = (id?: string | null) => designCatalog.find(style=>style.id===id);
