'use client';
import { useState } from 'react';
import { ArrowRight, Check, Compass, Palette, Plus, Search, Sparkles } from 'lucide-react';
import { DesignPicker } from './design-picker';
import { DesignPreview } from './design-preview';
import { findDesignStyle } from './design-catalog';
import type { ProjectPlanning } from './planning-types';
import './project-planning.css';

const fields={type:'Proje tipi',difficulty:'Zorluk',mvpFit:'MVP uygunluğu',revenue:'Gelir yaklaşımı',audience:'İlk kullanıcı',priority:'Öncelik',scope:'Kapsam',solo:'Tek başına yapılabilirlik',technical:'Teknik ihtiyaç',designIntensity:'Tasarım yoğunluğu',contentIntensity:'İçerik yoğunluğu'} as const;
export function ProjectOverview({plan,tasks,nextAction,onTasks,onPlan,onChange,onResearch,onTask}:{plan?:ProjectPlanning;tasks:string[];nextAction?:string;onTasks:()=>void;onPlan:()=>void;onChange:(plan:ProjectPlanning)=>void;onResearch:()=>void;onTask:(title:string)=>void}) {
  const [picker,setPicker]=useState(false);
  if(!plan)return <section className="pp-root pp-empty"><Compass size={34}/><h2>Fikrine bir yön ver.</h2><p>Mevcut görevlerin olduğu gibi kalır. Birkaç seçimle projenin kapsamını ve görsel dilini belirleyebilirsin.</p><button type="button" className="pp-button pp-primary" onClick={onPlan}>Fikri geliştir <ArrowRight size={17}/></button></section>;
  const a=plan.analysis,style=findDesignStyle(plan.selectedStyle);
  const update=(change:Partial<ProjectPlanning>)=>onChange({...plan,...change,updatedAt:new Date().toISOString()});
  const taskList=(list:string[])=><ol className="pp-action-list">{list.map((text,index)=>{const exists=tasks.includes(text);return <li key={text}><span>{String(index+1).padStart(2,'0')}</span><p>{text}</p><button type="button" className="pp-icon-button" disabled={exists} aria-label={exists?`${text} zaten görevlerde`:`${text} görevini ekle`} onClick={()=>onTask(text)}>{exists?<Check size={17}/>:<Plus size={17}/>}</button></li>;})}</ol>;
  return <div className="pp-root pp-overview"><div className="pp-overview-toolbar"><span className="pp-fineprint">{plan.origin==='rebuild'?'AI ile üretilen proje planı · Sınıflandırma ve stil önerisi yerel değerlendirme':'Cevaplarına dayalı ön değerlendirme · AI üretimi değil'}</span><button type="button" className="pp-button" onClick={onPlan}><Compass size={16}/> Fikri yeniden değerlendir</button></div>
    <section className="pp-panel"><span className="pp-kicker">SIRADAKİ ADIM</span><h2>{nextAction || (tasks.length?'İlk görevlerin tamamlandı.':'Henüz görev eklenmedi.')}</h2><p>{nextAction?'Tamamladıkça sıradaki açık iş burada görünür.':'Sonuçları değerlendir, gerekirse yeni bir adım ekle.'}</p><button type="button" className="pp-button" onClick={onTasks}>Görevleri aç <ArrowRight size={16}/></button></section>
    <div className="pp-overview-grid"><section className="pp-panel pp-route-panel"><span className="pp-kicker">ÖNERİLEN YOL</span><h2>{a.route}</h2><p>{a.routeReason}</p><div className="pp-route-actions"><button type="button" className="pp-button pp-primary" onClick={()=>update({lifecycle:'mvp'})}>MVP’ye indir <ArrowRight size={16}/></button><button type="button" className="pp-button" onClick={()=>update({lifecycle:'paused'})}>Daha sonra bak</button></div><details><summary>Değerlendirilen fikir</summary><p>{a.summary}</p></details></section>
      <section className="pp-panel pp-current-style"><div className="pp-section-top"><span className="pp-kicker">PROJENİN GÖRSEL DİLİ</span><Palette size={17}/></div>{style&&<><DesignPreview style={style}/><h3>{style.name}</h3><p>{style.description}</p></>}<button type="button" className="pp-button" aria-expanded={picker} onClick={()=>setPicker(!picker)}>{picker?'Stil seçimini kapat':'Tasarım dilini değiştir'}</button></section>
    </div>
    {picker&&<section className="pp-panel pp-picker-panel"><h2>Projenin karakterini seç.</h2><DesignPicker selected={plan.selectedStyle} recommendations={a.recommendations} onSelect={id=>update({selectedStyle:id})}/></section>}
    <section className="pp-panel pp-classification"><div><h2>Projenin profili</h2><p>Önerilen sınıflandırmalar. Birini değiştirmek için düzenlemeyi aç.</p></div><dl>{(['type','audience','scope','priority'] as const).map(key=><div key={key}><dt>{fields[key]}</dt><dd>{plan.overrides[key]||a[key]}</dd></div>)}</dl><details><summary>Tüm sınıflandırmaları gör ve düzenle</summary><div className="pp-profile-fields">{Object.entries(fields).map(([key,label])=><label className="pp-field" key={key}>{label}<input maxLength={240} value={plan.overrides[key as keyof typeof fields]??a[key as keyof typeof fields]} onChange={e=>update({overrides:{...plan.overrides,[key]:e.target.value}})}/></label>)}</div><button type="button" className="pp-button" onClick={()=>{if(window.confirm('Elle düzenlediğin sınıflandırmalar sistem önerilerine dönsün mü?'))update({overrides:{}});}}>Sistem önerilerine dön</button></details></section>
    <div className="pp-overview-grid"><section className="pp-panel"><span className="pp-kicker">ŞİMDİ</span><h2>İlk üç adım</h2>{taskList(a.firstSteps)}<details><summary>Sonraki hafta için</summary>{taskList(a.nextWeek)}</details></section><section className="pp-panel"><span className="pp-kicker">EN KÜÇÜK İŞE YARAR SÜRÜM</span><h2>MVP sınırı</h2><p>{a.mvp}</p><h3>Gerekli araç yaklaşımı</h3><ul>{a.technologies.map(text=><li key={text}>{text}</li>)}</ul></section></div>
    <section className="pp-panel"><div className="pp-section-top"><div><span className="pp-kicker">BİLMEDİKLERİMİZ</span><h2>Araştırılacak sorular</h2></div><button type="button" className="pp-button" onClick={onResearch}><Search size={16}/>{plan.researchId?'Araştırmayı aç':'Araştırmaya ekle'}</button></div><ul className="pp-research-list">{a.research.map(q=><li key={q}>{q}</li>)}</ul><p className="pp-fineprint">Proje değerlendirmesinden oluşturulan başlangıç soruları; rakip taraması veya doğrulanmış pazar bulgusu değildir. Araştırma kaydında notlarını ve ilerlemeni saklayabilirsin.</p></section>
    <div className="pp-overview-grid"><section className="pp-panel"><h2>Görsel uygulama notları</h2>{style?<><p><Sparkles size={15}/> Seçili {style.name} diline göre:</p><ul>{style.principles.map(text=><li key={text}>{text}</li>)}</ul></>:<p>Önce bir tasarım dili seç.</p>}<h3>Alternatif yaklaşımlar</h3>{a.recommendations.filter(r=>r.styleId!==plan.selectedStyle).map(r=>{const alternative=findDesignStyle(r.styleId);return alternative?<details key={r.styleId}><summary>{alternative.name}</summary><p>{r.reason}</p><button type="button" className="pp-button" onClick={()=>update({selectedStyle:r.styleId})}>Bu stile geç</button></details>:null;})}</section><section className="pp-panel"><h2>Gözden kaçmasın</h2><ul>{a.risks.map(text=><li key={text}>{text}</li>)}</ul><details><summary>Sonra eklenebilecekler</summary>{taskList(a.features)}</details><p className="pp-fineprint">Çalışma notları, kararlar ve bağlantılar için “Notlar ve bağlantılar” sekmesini kullan.</p></section></div>
  </div>;
}
