'use client';

/* Private images are served by the authenticated media endpoint. */
/* eslint-disable @next/next/no-img-element */
import { useState } from 'react';
import { ExternalLink, ImagePlus, Link2, LoaderCircle, Plus, Trash2 } from 'lucide-react';
import type { ProjectNote, ProjectNoteKind, ProjectPhoto, ProjectWorkspaceData } from './project-types';
import { safeResourceUrl } from './project-types';

const templates:Record<ProjectNoteKind,{label:string;description:string;context:string;body:string;outcome:string;next:string}>={
  decision:{label:'Karar',description:'Neyi, neden seçtiğini daha sonra da anlayabil.',context:'Kararı gerektiren durum neydi?',body:'Hangi seçenekleri değerlendirdin?',outcome:'Ne kararı aldın ve neden?',next:'Bu kararın ilk uygulama adımı ne?'},
  meeting:{label:'Toplantı',description:'Konuşulanı eyleme ve sorumluluğa dönüştür.',context:'Toplantının amacı ve katılanlar',body:'Önemli konuşma notları',outcome:'Alınan kararlar',next:'Kim, neyi, ne zamana kadar yapacak?'},
  idea:{label:'Fikir',description:'Ham fikri probleme ve değere bağla.',context:'Hangi problemi veya fırsatı fark ettin?',body:'Fikir nasıl çalışır?',outcome:'Neden değerli olabilir?',next:'En küçük nasıl deneyebilirsin?'},
  research:{label:'Araştırma',description:'Proje için bulguyu karara bağla.',context:'Cevap aradığın proje sorusu',body:'Bulduğun kanıt ve örnekler',outcome:'Bu bulgu projeyi nasıl etkiliyor?',next:'Doğrulanması gereken sonraki şey'}
};

function NoteCard({note,onChange,onDelete,onError}:{note:ProjectNote;onChange:(change:Partial<ProjectNote>)=>void;onDelete:()=>void;onError:(message:string)=>void}){
  const template=templates[note.kind];const [link,setLink]=useState({title:'',url:''}),[busy,setBusy]=useState(false);
  const upload=async(file:File)=>{if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024){onError('En fazla 10 MB boyutunda JPG, PNG veya WebP seç.');return;}setBusy(true);try{const response=await fetch('/api/project-media',{method:'POST',headers:{'Content-Type':file.type},body:file,signal:AbortSignal.timeout(60000)});const data=await response.json() as ProjectPhoto&{error?:string};if(!response.ok||!data.id||!data.url)throw new Error(data.error||'Görsel yüklenemedi.');onChange({images:[...note.images,{...data,name:file.name,caption:''}]});}catch(cause){onError(cause instanceof Error?cause.message:'Görsel yüklenemedi.');}finally{setBusy(false);}};
  return <details className="pn-note" open><summary><span className={`pn-kind ${note.kind}`}>{template.label}</span><div><strong>{note.title||'Başlıksız not'}</strong><small>{template.description}</small></div></summary><div className="pn-note-body"><label>Not başlığı<input maxLength={160} value={note.title} onChange={event=>onChange({title:event.target.value})} placeholder={`${template.label} başlığı`}/></label><div className="pn-guided-grid"><label>{template.context}<textarea rows={3} maxLength={4000} value={note.context} onChange={event=>onChange({context:event.target.value})}/></label><label>{template.body}<textarea rows={3} maxLength={8000} value={note.body} onChange={event=>onChange({body:event.target.value})}/></label><label>{template.outcome}<textarea rows={3} maxLength={4000} value={note.outcome} onChange={event=>onChange({outcome:event.target.value})}/></label><label>{template.next}<textarea rows={3} maxLength={3000} value={note.nextStep} onChange={event=>onChange({nextStep:event.target.value})}/></label></div>
    <section className="pn-attachments"><div className="pn-attach-title"><div><strong>Bu nota ait referanslar</strong><small>Projenin genel bağlantı rafından ayrı tutulur.</small></div><label className="pn-upload">{busy?<LoaderCircle size={15}/>:<ImagePlus size={15}/>} {busy?'Yükleniyor…':'Görsel ekle'}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={event=>{const file=event.target.files?.[0];event.target.value='';if(file)void upload(file);}}/></label></div><form className="pn-link-form" onSubmit={event=>{event.preventDefault();const url=safeResourceUrl(link.url);if(!url){onError('http:// veya https:// ile başlayan geçerli bir bağlantı gir.');return;}onChange({links:[...note.links,{id:crypto.randomUUID(),title:link.title.trim()||new URL(url).hostname,url}]});setLink({title:'',url:''});}}><input aria-label="Bağlantı başlığı" value={link.title} onChange={event=>setLink({...link,title:event.target.value})} placeholder="Bağlantı başlığı"/><input aria-label="Bağlantı adresi" type="url" value={link.url} onChange={event=>setLink({...link,url:event.target.value})} placeholder="https://…"/><button disabled={!link.url.trim()}><Link2 size={14}/> Ekle</button></form><div className="pn-links">{note.links.map(item=><span key={item.id}><a href={safeResourceUrl(item.url)||undefined} target="_blank" rel="noopener noreferrer"><ExternalLink size={13}/>{item.title}</a><button aria-label={`${item.title} bağlantısını kaldır`} onClick={()=>onChange({links:note.links.filter(link=>link.id!==item.id)})}><Trash2 size={12}/></button></span>)}</div><div className="pn-images">{note.images.map(item=><figure key={item.id}><img src={item.url} alt={item.caption||item.name}/><input aria-label={`${item.name} görsel açıklaması`} value={item.caption} onChange={event=>onChange({images:note.images.map(image=>image.id===item.id?{...image,caption:event.target.value.slice(0,500)}:image)})} placeholder="Görselin notu…"/><button aria-label={`${item.name} görselini kaldır`} onClick={()=>onChange({images:note.images.filter(image=>image.id!==item.id)})}><Trash2 size={13}/></button></figure>)}</div></section><button type="button" className="pw-delete" onClick={onDelete}><Trash2 size={14}/> Notu sil</button></div></details>;
}

export function ProjectNotebook({workspace,onChange,onError}:{workspace:ProjectWorkspaceData;onChange:(update:(current:ProjectWorkspaceData)=>ProjectWorkspaceData)=>void;onError:(message:string)=>void}){
  const [kind,setKind]=useState<ProjectNoteKind>('decision');
  const add=()=>{const note:ProjectNote={id:crypto.randomUUID(),title:`Yeni ${templates[kind].label.toLocaleLowerCase('tr-TR')} notu`,kind,body:'',context:'',outcome:'',nextStep:'',links:[],images:[]};onChange(current=>({...current,notes:[note,...current.notes]}));};
  return <section className="surface pw-resource pn-notebook"><div className="pw-section-heading"><div><h2>Proje defteri</h2><p>Not türünü seç; Orbit neyi kaydetmen gerektiğini hatırlatsın.</p></div></div><div className="pn-template-picker">{(Object.entries(templates) as [ProjectNoteKind,typeof templates[ProjectNoteKind]][]).map(([id,item])=><button key={id} className={kind===id?'active':''} onClick={()=>setKind(id)}><strong>{item.label}</strong><small>{item.description}</small></button>)}</div><button className="pn-add" onClick={add}><Plus size={16}/> {templates[kind].label} notu oluştur</button>{!workspace.notes.length&&<div className="pn-empty"><strong>Boş sayfayla başlama.</strong><span>Yukarıdan notun amacını seç; sana uygun iskelet hazır gelsin.</span></div>}<div className="pn-list">{workspace.notes.map(note=><NoteCard key={note.id} note={note} onError={onError} onChange={change=>onChange(current=>({...current,notes:current.notes.map(item=>item.id===note.id?{...item,...change}:item)}))} onDelete={()=>{if(window.confirm('Bu proje notu silinsin mi?'))onChange(current=>({...current,notes:current.notes.filter(item=>item.id!==note.id)}));}}/>)}</div></section>;
}
