'use client';
import { useState } from 'react';
import { ArrowRight, Check, ClipboardCopy, Compass, Palette, Plus, Search, ChevronDown } from 'lucide-react';
import { DesignPicker } from './design-picker';
import { DesignPreview } from './design-preview';
import { findDesignStyle } from './design-catalog';
import type { ProjectPlanning } from './planning-types';
import './project-planning.css';

const fields = {type:'Proje tipi',difficulty:'Zorluk',mvpFit:'MVP uygunluğu',revenue:'Gelir yaklaşımı',audience:'İlk kullanıcı',priority:'Öncelik',scope:'Kapsam',solo:'Tek başına yapılabilirlik',technical:'Teknik ihtiyaç',designIntensity:'Tasarım yoğunluğu',contentIntensity:'İçerik yoğunluğu'} as const;
export function ProjectOverview({plan,tasks,onPlan,onChange,onResearch,onTask,onCopyTask}:{plan?:ProjectPlanning;tasks:string[];onPlan:()=>void;onChange:(plan:ProjectPlanning)=>void;onResearch:()=>void;onTask:(title:string)=>void;onCopyTask:(title:string)=>void}) {
  const [picker,setPicker]=useState(false);
  if(!plan)return <section className="pp-root pp-empty"><Compass size={30}/><h2>Bu projenin yolunu netleştir.</h2><p>Hazır olduğunda kapsam, tasarım ve başlangıç önerilerini burada oluşturabilirsin.</p><button type="button" className="pp-button pp-primary" onClick={onPlan}>Plan oluştur <ArrowRight size={17}/></button></section>;
  const a=plan.analysis,style=findDesignStyle(plan.selectedStyle);
  const update=(change:Partial<ProjectPlanning>)=>onChange({...plan,...change,updatedAt:new Date().toISOString()});
  const taskList=(list:string[])=><ol className="pp-action-list">{list.map((text,index)=>{const exists=tasks.includes(text);return <li key={text}><span>{String(index+1).padStart(2,'0')}</span><p>{text}</p><button type="button" className="pp-icon-button" title="Kopyala" aria-label={`${text} görevini kopyala`} onClick={()=>onCopyTask(text)}><ClipboardCopy size={17}/></button><button type="button" className="pp-icon-button" disabled={exists} aria-label={exists?`${text} zaten görevlerde`:`${text} görevini ekle`} onClick={()=>onTask(text)}>{exists?<Check size={17}/>:<Plus size={17}/>}</button></li>;})}</ol>;
  return <div className="pp-root px-plan">
    <div className="px-section-title"><div><h2>Projenin planı</h2><p>Kapsamı hatırla, ihtiyaç duyduğun bölümü aç.</p></div><button type="button" className="pp-button" onClick={onPlan}><Compass size={16}/> Planı güncelle</button></div>
    <section className="px-brief"><span className="pp-kicker">İLK HEDEF</span><h2>{a.route}</h2><p>{a.summary}</p><div><span>İlk sürümün sınırı</span><p>{a.mvp}</p></div></section>
    <details className="px-disclosure"><summary><Compass size={19}/><span><strong>Yol haritası</strong><small>Önerilen adımlar, araçlar ve sonraki fikirler</small></span><ChevronDown size={18}/></summary><div className="px-disclosure-content"><p>{a.routeReason}</p><h3>Başlangıç adımları</h3>{taskList(a.firstSteps)}<details><summary>Sonraki hafta</summary>{taskList(a.nextWeek)}</details><details><summary>Gerekli araçlar</summary><ul>{a.technologies.map(text=><li key={text}>{text}</li>)}</ul></details><details><summary>Sonra eklenebilecekler</summary>{taskList(a.features)}</details><button type="button" className="pp-button" onClick={()=>update({lifecycle:'mvp'})}>İlk sürüme odaklan</button></div></details>
    <details className="px-disclosure"><summary><Palette size={19}/><span><strong>Tasarım dili</strong><small>{style?.name || 'Henüz bir stil seçilmedi'} · Görsel örnekler ve uygulama notları</small></span><ChevronDown size={18}/></summary><div className="px-disclosure-content">{style&&<div className="px-style-summary"><DesignPreview style={style}/><div><h3>{style.name}</h3><p>{style.description}</p><ul>{style.principles.map(text=><li key={text}>{text}</li>)}</ul></div></div>}<button type="button" className="pp-button" aria-expanded={picker} onClick={()=>setPicker(!picker)}>{picker?'Stil seçimini kapat':'Tasarım dilini değiştir'}</button>{picker&&<DesignPicker selected={plan.selectedStyle} recommendations={a.recommendations} onSelect={id=>update({selectedStyle:id})}/>}</div></details>
    <details className="px-disclosure"><summary><Search size={19}/><span><strong>Araştırma ve riskler</strong><small>{a.research.length} soru · Doğrulanması gereken noktalar</small></span><ChevronDown size={18}/></summary><div className="px-disclosure-content"><ul>{a.research.map(q=><li key={q}>{q}</li>)}</ul><button type="button" className="pp-button" onClick={onResearch}><Search size={16}/>{plan.researchId?'Araştırmayı aç':'Araştırmaya ekle'}</button><h3>Gözden kaçmasın</h3><ul>{a.risks.map(text=><li key={text}>{text}</li>)}</ul><p className="pp-fineprint">Bunlar başlangıç soruları ve ön değerlendirmelerdir; doğrulanmış pazar bulguları değildir.</p></div></details>
    <details className="px-disclosure"><summary><ClipboardCopy size={19}/><span><strong>Proje profili</strong><small>Hedef kitle, kapsam, teknik ihtiyaçlar ve diğer ayrıntılar</small></span><ChevronDown size={18}/></summary><div className="px-disclosure-content"><div className="pp-profile-fields">{Object.entries(fields).map(([key,label])=><label className="pp-field" key={key}>{label}<input maxLength={240} value={plan.overrides[key as keyof typeof fields]??a[key as keyof typeof fields]} onChange={e=>update({overrides:{...plan.overrides,[key]:e.target.value}})}/></label>)}</div><button type="button" className="pp-button" onClick={()=>{if(window.confirm('Elle düzenlediğin sınıflandırmalar sistem önerilerine dönsün mü?'))update({overrides:{}});}}>Sistem önerilerine dön</button></div></details>
    <p className="pp-fineprint px-plan-source">{plan.origin==='rebuild'?'AI ile üretilen plan; sınıflandırma ve stil önerileri yerel değerlendirmedir.':'Cevaplarına dayalı ön değerlendirme; AI üretimi değildir.'}</p>
  </div>;
}
