'use client';

/* Private images are served by the authenticated media endpoint. */
/* eslint-disable @next/next/no-img-element */

import { useMemo, useState } from 'react';
import { useNavigationState } from '../use-navigation';
import { BookOpen, Check, ChevronDown, ExternalLink, FileQuestion, ImagePlus, Link2, LoaderCircle, Plus, RotateCcw, Sparkles, Trash2 } from 'lucide-react';
import type { ResearchTopic } from './practice-model';
import { angleLabels, generateResearchQuiz } from './research-quiz';

type Props={topic:ResearchTopic;onChange:(change:(topic:ResearchTopic)=>ResearchTopic)=>void};
const safeUrl=(value:string)=>{try{const url=new URL(value.trim());return ['http:','https:'].includes(url.protocol)&&!url.username&&!url.password?url.href:null;}catch{return null;}};

export function ResearchNotebook({topic,onChange}:Props){
  const [tab,setTab]=useNavigationState<'notes'|'sources'|'quiz'>(`research:${topic.id}:tab`,'notes');
  const [source,setSource]=useState({title:'',url:'',note:''});
  const [busy,setBusy]=useState(false),[error,setError]=useState('');
  const [revealed,setRevealed]=useState<string[]>([]);
  const filled=useMemo(()=>topic.questions.filter(q=>q.note.trim()||q.evidence.trim()||q.implication.trim()).length,[topic.questions]);
  const hasMaterial=filled>0||topic.synthesis.explanation.trim().length>30||topic.sources.some(item=>item.note.trim());
  const scored=topic.quiz?.questions.filter(question=>question.rating).length||0;
  const known=topic.quiz?.questions.filter(question=>question.rating==='known').length||0;
  const updateQuestion=(id:string,change:Partial<ResearchTopic['questions'][number]>)=>onChange(current=>({...current,questions:current.questions.map(question=>question.id===id?{...question,...change}:question)}));
  const buildQuiz=async()=>{setBusy(true);setError('');try{const quiz=await generateResearchQuiz(topic);onChange(current=>({...current,quiz}));setRevealed([]);}catch(cause){setError(cause instanceof Error?cause.message:'Test hazırlanamadı.');}finally{setBusy(false);}};
  const uploadImage=async(file:File)=>{
    if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024){setError('En fazla 10 MB boyutunda JPG, PNG veya WebP seç.');return;}
    setBusy(true);setError('');
    try{const response=await fetch('/api/project-media',{method:'POST',headers:{'Content-Type':file.type},body:file,signal:AbortSignal.timeout(60000)});const data=await response.json() as {id?:string;url?:string;createdAt?:string;error?:string};if(!response.ok||!data.id||!data.url)throw new Error(data.error||'Görsel yüklenemedi.');onChange(current=>({...current,images:[...current.images,{id:data.id!,url:data.url!,name:file.name,caption:'',createdAt:data.createdAt||new Date().toISOString()}]}));}
    catch(cause){setError(cause instanceof Error?cause.message:'Görsel yüklenemedi.');}finally{setBusy(false);}
  };
  return <div className="rn-shell">
    <header className="rn-heading"><div><span>ARAŞTIRMA DEFTERİ</span><h3>{topic.title}</h3><p>Bilgiyi kopyalamak yerine kendi cümlenle işle; sonra kendini test et.</p></div><div className="rn-progress"><strong>{filled}/{topic.questions.length}</strong><small>soru işlendi</small></div></header>
    <nav className="rn-tabs" aria-label="Araştırma defteri bölümleri"><button className={tab==='notes'?'active':''} onClick={()=>setTab('notes')}><BookOpen size={15}/> Not al</button><button className={tab==='sources'?'active':''} onClick={()=>setTab('sources')}><Link2 size={15}/> Kaynaklar <span>{topic.sources.length+topic.images.length}</span></button><button className={tab==='quiz'?'active':''} onClick={()=>setTab('quiz')}><FileQuestion size={15}/> Kendini test et</button></nav>
    {error&&<p className="rn-error" role="alert">{error}</p>}
    {tab==='notes'&&<div className="rn-notes">
      <div className="rn-guide"><strong>Her soruda aynı dört adım</strong><span>Önce anladığını yaz → kanıtı ayır → ne anlama geldiğini çıkar → açığı kaydet.</span></div>
      {topic.questions.map((question,index)=><details className="rn-question" key={question.id} open={index===0&&!question.note}><summary><button type="button" aria-label={`${question.text}: tamamlanma durumunu değiştir`} aria-pressed={question.explored} onClick={event=>{event.preventDefault();updateQuestion(question.id,{explored:!question.explored});}}>{question.explored&&<Check size={13}/>}</button><span><small>SORU {String(index+1).padStart(2,'0')}</small><strong>{question.text}</strong></span><ChevronDown size={17}/></summary><div className="rn-fields"><label className="wide">Kendi cümlemle cevap<textarea rows={4} value={question.note} onChange={event=>updateQuestion(question.id,{note:event.target.value.slice(0,4000)})} placeholder="Kaynağı kapatıp, gerçekten anladığın biçimde açıkla…"/></label><label>Kanıt / bulgu<textarea rows={3} value={question.evidence} onChange={event=>updateQuestion(question.id,{evidence:event.target.value.slice(0,4000)})} placeholder="Veri, örnek, alıntı özeti veya gözlem…"/></label><label>Bunun anlamı<textarea rows={3} value={question.implication} onChange={event=>updateQuestion(question.id,{implication:event.target.value.slice(0,4000)})} placeholder="Bu bulgu ana soruyu nasıl değiştiriyor?"/></label><label className="wide">Açık kalan nokta<input value={question.unknown} onChange={event=>updateQuestion(question.id,{unknown:event.target.value.slice(0,2000)})} placeholder="Hâlâ neyi bilmiyorum? Bir sonraki arama ne olmalı?"/></label></div></details>)}
      <section className="rn-synthesis"><div><span>SONUÇ</span><h4>Parçaları birleştir.</h4></div><label>Konuyu bir arkadaşına nasıl anlatırsın?<textarea rows={5} value={topic.synthesis.explanation} onChange={event=>onChange(current=>({...current,synthesis:{...current.synthesis,explanation:event.target.value.slice(0,8000)}}))} placeholder="Jargonsuz, kısa ve kendi cümlelerinle…"/></label><div className="rn-fields"><label>En önemli noktalar<textarea rows={4} value={topic.synthesis.keyPoints} onChange={event=>onChange(current=>({...current,synthesis:{...current.synthesis,keyPoints:event.target.value.slice(0,5000)}}))} placeholder={'Her satıra bir çıkarım\nNeden önemli olduğunu da yaz'}/></label><label>Açık sorular<textarea rows={4} value={topic.synthesis.openQuestions} onChange={event=>onChange(current=>({...current,synthesis:{...current.synthesis,openQuestions:event.target.value.slice(0,5000)}}))} placeholder="Araştırma bitmediğinde geriye ne kaldı?"/></label></div></section>
    </div>}
    {tab==='sources'&&<div className="rn-sources"><section className="rn-source-form"><div><span>KAYNAK EKLE</span><h4>Bulduğun şeyin izini kaybetme.</h4></div><div className="rn-fields"><label>Başlık<input value={source.title} onChange={event=>setSource({...source,title:event.target.value})} placeholder="Makale, video veya araç adı"/></label><label>Bağlantı<input type="url" value={source.url} onChange={event=>setSource({...source,url:event.target.value})} placeholder="https://…"/></label><label className="wide">Bu kaynak bana ne verdi?<textarea rows={2} value={source.note} onChange={event=>setSource({...source,note:event.target.value})} placeholder="Kopyalamak yerine bir cümleyle değerini yaz…"/></label></div><button disabled={!source.url.trim()} onClick={()=>{const url=safeUrl(source.url);if(!url){setError('http:// veya https:// ile başlayan geçerli bir bağlantı gir.');return;}onChange(current=>({...current,sources:[...current.sources,{id:crypto.randomUUID(),title:source.title.trim()||new URL(url).hostname,url,note:source.note.trim()}]}));setSource({title:'',url:'',note:''});setError('');}}><Plus size={15}/> Kaynağı ekle</button></section>
      <div className="rn-source-list">{topic.sources.map(item=><article key={item.id}><a href={safeUrl(item.url)||undefined} target="_blank" rel="noopener noreferrer"><ExternalLink size={15}/><span><strong>{item.title}</strong><small>{item.url}</small></span></a><textarea aria-label={`${item.title} kaynak notu`} rows={2} value={item.note} onChange={event=>onChange(current=>({...current,sources:current.sources.map(source=>source.id===item.id?{...source,note:event.target.value.slice(0,1000)}:source)}))} placeholder="Bu kaynaktan aldığım…"/><button aria-label={`${item.title} kaynağını kaldır`} onClick={()=>onChange(current=>({...current,sources:current.sources.filter(source=>source.id!==item.id)}))}><Trash2 size={14}/></button></article>)}</div>
      <section className="rn-image-shelf"><div><span>GÖRSEL RAFI</span><h4>Ekran görüntüsü, şema veya referans ekle.</h4></div><label className="rn-upload"><ImagePlus size={18}/>{busy?'Yükleniyor…':'Görsel seç'}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={event=>{const file=event.target.files?.[0];event.target.value='';if(file)void uploadImage(file);}}/></label><div className="rn-images">{topic.images.map(item=><figure key={item.id}><img src={item.url} alt={item.caption||item.name}/><input aria-label={`${item.name} görsel açıklaması`} value={item.caption} onChange={event=>onChange(current=>({...current,images:current.images.map(image=>image.id===item.id?{...image,caption:event.target.value.slice(0,500)}:image)}))} placeholder="Bu görsel neyi gösteriyor?"/><button aria-label={`${item.name} görselini kaldır`} onClick={()=>onChange(current=>({...current,images:current.images.filter(image=>image.id!==item.id)}))}><Trash2 size={14}/></button></figure>)}</div></section>
    </div>}
    {tab==='quiz'&&<div className="rn-quiz">
      {!topic.quiz?<section className="rn-quiz-start"><Sparkles size={25}/><span>AKTİF HATIRLAMA</span><h4>Gerçekten öğrendin mi?</h4><p>Orbit notlarından neden, nasıl, karşılaştırma ve uygulama soruları üretir. Cevabı yazmadan anahtar noktaları göremezsin.</p><button disabled={!hasMaterial||busy} onClick={()=>void buildQuiz()}>{busy?<><LoaderCircle className="rn-spin" size={16}/> Hazırlanıyor…</>:<><FileQuestion size={16}/> Konuma özel test hazırla</>}</button>{!hasMaterial&&<small>Önce en az bir araştırma sorusuna kendi cümlelerinle not ekle.</small>}</section>:
      <><header className="rn-quiz-summary"><div><span>ÖĞRENME TESTİ</span><h4>{scored===topic.quiz.questions.length?`${known}/${topic.quiz.questions.length} soru sağlam`:'Cevabı hafızandan kur.'}</h4><p>{scored}/{topic.quiz.questions.length} değerlendirildi · {new Date(topic.quiz.generatedAt).toLocaleDateString('tr-TR')}</p></div><button disabled={busy} onClick={()=>void buildQuiz()}><RotateCcw size={14}/> Yeni test</button></header><div className="rn-quiz-list">{topic.quiz.questions.map((question,index)=>{const show=revealed.includes(question.id);return <article key={question.id} className={question.rating?`rated ${question.rating}`:''}><div className="rn-quiz-label"><span>{String(index+1).padStart(2,'0')} · {angleLabels[question.angle]}</span>{question.rating&&<em>{question.rating==='known'?'Biliyorum':question.rating==='partial'?'Kısmen':'Tekrar et'}</em>}</div><h5>{question.prompt}</h5>{question.hint&&<details className="rn-hint"><summary>İpucu</summary><p>{question.hint}</p></details>}<textarea rows={4} value={question.answer} onChange={event=>onChange(current=>({...current,quiz:current.quiz?{...current.quiz,questions:current.quiz.questions.map(item=>item.id===question.id?{...item,answer:event.target.value.slice(0,4000)}:item)}:null}))} placeholder="Kaynaklara bakmadan cevapla…"/>{!show?<button disabled={!question.answer.trim()} onClick={()=>setRevealed(current=>[...current,question.id])}>Anahtar noktaları göster</button>:<div className="rn-key"><strong>Cevabında bunlar var mı?</strong><ul>{question.keyPoints.map(point=><li key={point}>{point}</li>)}</ul><div><button onClick={()=>onChange(current=>({...current,quiz:current.quiz?{...current.quiz,questions:current.quiz.questions.map(item=>item.id===question.id?{...item,rating:'again'}:item)}:null}))}>Tekrar et</button><button onClick={()=>onChange(current=>({...current,quiz:current.quiz?{...current.quiz,questions:current.quiz.questions.map(item=>item.id===question.id?{...item,rating:'partial'}:item)}:null}))}>Kısmen</button><button onClick={()=>onChange(current=>({...current,quiz:current.quiz?{...current.quiz,questions:current.quiz.questions.map(item=>item.id===question.id?{...item,rating:'known'}:item)}:null}))}>Biliyorum</button></div></div>}</article>;})}</div></>}
    </div>}
  </div>;
}
