'use client';

/* Private images are served by the authenticated media endpoint. */
/* eslint-disable @next/next/no-img-element */

import { useMemo, useState } from 'react';
import { useNavigationState } from '../use-navigation';
import { ArrowLeft, ArrowRight, BookOpen, Check, ChevronDown, ExternalLink, FileQuestion, ImagePlus, Link2, LoaderCircle, Plus, RotateCcw, Sparkles, Trash2 } from 'lucide-react';
import type { ResearchTopic } from './practice-model';
import { angleLabels, generateResearchQuiz } from './research-quiz';

type Props={topic:ResearchTopic;onChange:(change:(topic:ResearchTopic)=>ResearchTopic)=>void};
const safeUrl=(value:string)=>{try{const url=new URL(value.trim());return ['http:','https:'].includes(url.protocol)&&!url.username&&!url.password?url.href:null;}catch{return null;}};

export function ResearchNotebook({topic,onChange}:Props){
  const [tab,setTab]=useNavigationState<'notes'|'sources'|'quiz'|'result'>(`research:${topic.id}:tab`,'notes');
  const [selectedQuestion,setSelectedQuestion]=useNavigationState<string>(`research:${topic.id}:question`,()=>topic.questions.find(q=>!q.explored)?.id||topic.questions[0]?.id||'',false,true);
  const questionIndex=Math.max(0,topic.questions.findIndex(q=>q.id===selectedQuestion));
  const activeQuestion=topic.questions[questionIndex];
  const [quizIndex,setQuizIndex]=useNavigationState<number>(`research:${topic.id}:quizIndex`,0);
  const [source,setSource]=useState({title:'',url:'',note:''});
  const [busy,setBusy]=useState(false),[error,setError]=useState('');
  const [revealed,setRevealed]=useState<string[]>([]);
  const filled=useMemo(()=>topic.questions.filter(q=>q.note.trim()||q.evidence.trim()||q.implication.trim()).length,[topic.questions]);
  const hasMaterial=filled>0||topic.synthesis.explanation.trim().length>30||topic.sources.some(item=>item.note.trim());
  const scored=topic.quiz?.questions.filter(question=>question.rating).length||0;
  const known=topic.quiz?.questions.filter(question=>question.rating==='known').length||0;
  const updateQuestion=(id:string,change:Partial<ResearchTopic['questions'][number]>)=>onChange(current=>({...current,questions:current.questions.map(question=>question.id===id?{...question,...change}:question)}));
  const buildQuiz=async()=>{setBusy(true);setError('');try{const quiz=await generateResearchQuiz(topic);onChange(current=>({...current,quiz}));setRevealed([]);setQuizIndex(0);}catch(cause){setError(cause instanceof Error?cause.message:'Test hazırlanamadı.');}finally{setBusy(false);}};
  const uploadImage=async(file:File)=>{
    if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024){setError('En fazla 10 MB boyutunda JPG, PNG veya WebP seç.');return;}
    setBusy(true);setError('');
    try{const response=await fetch('/api/project-media',{method:'POST',headers:{'Content-Type':file.type},body:file,signal:AbortSignal.timeout(60000)});const data=await response.json() as {id?:string;url?:string;createdAt?:string;error?:string};if(!response.ok||!data.id||!data.url)throw new Error(data.error||'Görsel yüklenemedi.');onChange(current=>({...current,images:[...current.images,{id:data.id!,url:data.url!,name:file.name,caption:'',createdAt:data.createdAt||new Date().toISOString()}]}));}
    catch(cause){setError(cause instanceof Error?cause.message:'Görsel yüklenemedi.');}finally{setBusy(false);}
  };
  return <div className="rn-shell">
    <header className="rn-heading"><div><span>ARAŞTIRMA DEFTERİ</span><h3>{topic.title}</h3><p>Bir soruya odaklan. Kendi cümlenle yaz, sonra hatırlamayı dene.</p></div><div className="rn-progress"><strong>{topic.questions.filter(q=>q.explored).length}/{topic.questions.length}</strong><small>soru tamamlandı</small></div></header>
    <nav className="rn-tabs" aria-label="Araştırma defteri bölümleri"><button aria-pressed={tab==='notes'} className={tab==='notes'?'active':''} onClick={()=>setTab('notes')}><BookOpen size={15}/> Sorular</button><button aria-pressed={tab==='sources'} className={tab==='sources'?'active':''} onClick={()=>setTab('sources')}><Link2 size={15}/> Kaynaklar <span>{topic.sources.length+topic.images.length}</span></button><button aria-pressed={tab==='result'} className={tab==='result'?'active':''} onClick={()=>setTab('result')}><BookOpen size={15}/> Sonuç</button><button aria-pressed={tab==='quiz'} className={tab==='quiz'?'active':''} onClick={()=>setTab('quiz')}><FileQuestion size={15}/> Kendini test et</button></nav>
    <details className="rx-research-context"><summary>Araştırmanın ana sorusu</summary><p>{topic.question}</p></details>
    {error&&<p className="rn-error" role="alert">{error}</p>}
    {tab==='notes'&&<div className="rn-notes">
      <div className="rx-question-nav"><span>Soru {questionIndex+1} / {topic.questions.length}</span><div><button className="rd-icon" aria-label="Önceki araştırma sorusu" disabled={questionIndex===0} onClick={()=>setSelectedQuestion(topic.questions[questionIndex-1].id)}><ArrowLeft size={17}/></button><button className="rd-icon" aria-label="Sonraki araştırma sorusu" disabled={questionIndex>=topic.questions.length-1} onClick={()=>setSelectedQuestion(topic.questions[questionIndex+1].id)}><ArrowRight size={17}/></button></div></div>
      {activeQuestion&&<article className="rx-research-question" key={activeQuestion.id}><h4>{activeQuestion.text}</h4><label className="rx-answer-field">Ne öğrendin?<textarea rows={5} value={activeQuestion.note} onChange={event=>updateQuestion(activeQuestion.id,{note:event.target.value.slice(0,4000)})} placeholder="Kendi cümlelerinle kısa bir cevap yaz…"/></label><details className="rx-options"><summary>Kanıt, çıkarım ve açık noktalar</summary><div className="rn-fields"><label>Kanıt / bulgu<textarea rows={3} value={activeQuestion.evidence} onChange={event=>updateQuestion(activeQuestion.id,{evidence:event.target.value.slice(0,4000)})} placeholder="Veri, örnek veya gözlem…"/></label><label>Bunun anlamı<textarea rows={3} value={activeQuestion.implication} onChange={event=>updateQuestion(activeQuestion.id,{implication:event.target.value.slice(0,4000)})} placeholder="Bu bulgu neyi değiştiriyor?"/></label><label className="wide">Açık kalan nokta<input value={activeQuestion.unknown} onChange={event=>updateQuestion(activeQuestion.id,{unknown:event.target.value.slice(0,2000)})} placeholder="Hâlâ neyi bilmiyorum?"/></label></div></details><div className="rd-detail-actions"><button className={activeQuestion.explored?'rd-text-button':'rd-done-action'} aria-pressed={activeQuestion.explored} onClick={()=>updateQuestion(activeQuestion.id,{explored:!activeQuestion.explored})}><Check size={16}/>{activeQuestion.explored?'Tamamlandı · geri al':'Soruyu tamamladım'}</button>{questionIndex<topic.questions.length-1?<button className="rd-text-button" onClick={()=>setSelectedQuestion(topic.questions[questionIndex+1].id)}>Sonraki soru <ArrowRight size={16}/></button>:<button className="rd-text-button" onClick={()=>setTab('result')}>Sonucu yaz <ArrowRight size={16}/></button>}</div></article>}
      <details className="rx-options"><summary>Tüm araştırma soruları</summary><div className="rx-question-list">{topic.questions.map((question,index)=><button key={question.id} aria-current={question.id===activeQuestion?.id?'step':undefined} onClick={()=>setSelectedQuestion(question.id)}><span>{question.explored?<Check size={15}/>:String(index+1).padStart(2,'0')}</span><strong>{question.text}</strong><ChevronDown size={15}/></button>)}</div></details>
    </div>}
    {tab==='result'&&<div className="rn-notes">
      <section className="rn-synthesis"><div><span>SONUÇ</span><h4>Parçaları birleştir.</h4></div><label>Konuyu bir arkadaşına nasıl anlatırsın?<textarea rows={5} value={topic.synthesis.explanation} onChange={event=>onChange(current=>({...current,synthesis:{...current.synthesis,explanation:event.target.value.slice(0,8000)}}))} placeholder="Jargonsuz, kısa ve kendi cümlelerinle…"/></label><div className="rn-fields"><label>En önemli noktalar<textarea rows={4} value={topic.synthesis.keyPoints} onChange={event=>onChange(current=>({...current,synthesis:{...current.synthesis,keyPoints:event.target.value.slice(0,5000)}}))} placeholder={'Her satıra bir çıkarım\nNeden önemli olduğunu da yaz'}/></label><label>Açık sorular<textarea rows={4} value={topic.synthesis.openQuestions} onChange={event=>onChange(current=>({...current,synthesis:{...current.synthesis,openQuestions:event.target.value.slice(0,5000)}}))} placeholder="Araştırma bitmediğinde geriye ne kaldı?"/></label></div></section>
    </div>}
    {tab==='sources'&&<div className="rn-sources"><section className="rn-source-form"><div><span>KAYNAK EKLE</span><h4>Bulduğun şeyin izini kaybetme.</h4></div><div className="rn-fields"><label>Başlık<input value={source.title} onChange={event=>setSource({...source,title:event.target.value})} placeholder="Makale, video veya araç adı"/></label><label>Bağlantı<input type="url" value={source.url} onChange={event=>setSource({...source,url:event.target.value})} placeholder="https://…"/></label><label className="wide">Bu kaynak bana ne verdi?<textarea rows={2} value={source.note} onChange={event=>setSource({...source,note:event.target.value})} placeholder="Kopyalamak yerine bir cümleyle değerini yaz…"/></label></div><button disabled={!source.url.trim()} onClick={()=>{const url=safeUrl(source.url);if(!url){setError('http:// veya https:// ile başlayan geçerli bir bağlantı gir.');return;}onChange(current=>({...current,sources:[...current.sources,{id:crypto.randomUUID(),title:source.title.trim()||new URL(url).hostname,url,note:source.note.trim()}]}));setSource({title:'',url:'',note:''});setError('');}}><Plus size={15}/> Kaynağı ekle</button></section>
      <div className="rn-source-list">{topic.sources.map(item=><article key={item.id}><a href={safeUrl(item.url)||undefined} target="_blank" rel="noopener noreferrer"><ExternalLink size={15}/><span><strong>{item.title}</strong><small>{item.url}</small></span></a><textarea aria-label={`${item.title} kaynak notu`} rows={2} value={item.note} onChange={event=>onChange(current=>({...current,sources:current.sources.map(source=>source.id===item.id?{...source,note:event.target.value.slice(0,1000)}:source)}))} placeholder="Bu kaynaktan aldığım…"/><button aria-label={`${item.title} kaynağını kaldır`} onClick={()=>onChange(current=>({...current,sources:current.sources.filter(source=>source.id!==item.id)}))}><Trash2 size={14}/></button></article>)}</div>
      <section className="rn-image-shelf"><div><span>GÖRSEL RAFI</span><h4>Ekran görüntüsü, şema veya referans ekle.</h4></div><label className="rn-upload"><ImagePlus size={18}/>{busy?'Yükleniyor…':'Görsel seç'}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={event=>{const file=event.target.files?.[0];event.target.value='';if(file)void uploadImage(file);}}/></label><div className="rn-images">{topic.images.map(item=><figure key={item.id}><img src={item.url} alt={item.caption||item.name}/><input aria-label={`${item.name} görsel açıklaması`} value={item.caption} onChange={event=>onChange(current=>({...current,images:current.images.map(image=>image.id===item.id?{...image,caption:event.target.value.slice(0,500)}:image)}))} placeholder="Bu görsel neyi gösteriyor?"/><button aria-label={`${item.name} görselini kaldır`} onClick={()=>onChange(current=>({...current,images:current.images.filter(image=>image.id!==item.id)}))}><Trash2 size={14}/></button></figure>)}</div></section>
    </div>}
    {tab==='quiz'&&<div className="rn-quiz">
      {!topic.quiz?<section className="rn-quiz-start"><Sparkles size={25}/><span>AKTİF HATIRLAMA</span><h4>Gerçekten öğrendin mi?</h4><p>Orbit notlarından neden, nasıl, karşılaştırma ve uygulama soruları üretir. Cevabı yazmadan anahtar noktaları göremezsin.</p><button disabled={!hasMaterial||busy} onClick={()=>void buildQuiz()}>{busy?<><LoaderCircle className="rn-spin" size={16}/> Hazırlanıyor…</>:<><FileQuestion size={16}/> Konuma özel test hazırla</>}</button>{!hasMaterial&&<small>Önce en az bir araştırma sorusuna kendi cümlelerinle not ekle.</small>}</section>:
      <><header className="rn-quiz-summary"><div><span>ÖĞRENME TESTİ</span><h4>{scored===topic.quiz.questions.length?`${known}/${topic.quiz.questions.length} soru sağlam`:'Cevabı hafızandan kur.'}</h4><p>{scored}/{topic.quiz.questions.length} değerlendirildi · {new Date(topic.quiz.generatedAt).toLocaleDateString('tr-TR')}</p></div><button disabled={busy} onClick={()=>void buildQuiz()}><RotateCcw size={14}/> Yeni test</button></header><div className="rx-question-nav"><span>Soru {Math.min(quizIndex+1,topic.quiz.questions.length)} / {topic.quiz.questions.length}</span><div><button className="rd-icon" aria-label="Önceki test sorusu" disabled={quizIndex===0} onClick={()=>setQuizIndex(index=>index-1)}><ArrowLeft size={17}/></button><button className="rd-icon" aria-label="Sonraki test sorusu" disabled={quizIndex>=topic.quiz.questions.length-1} onClick={()=>setQuizIndex(index=>index+1)}><ArrowRight size={17}/></button></div></div><div className="rn-quiz-list">{topic.quiz.questions.slice(Math.min(quizIndex,topic.quiz.questions.length-1),Math.min(quizIndex,topic.quiz.questions.length-1)+1).map((question)=>{const index=Math.min(quizIndex,topic.quiz!.questions.length-1);const show=revealed.includes(question.id);return <article key={question.id} className={question.rating?`rated ${question.rating}`:''}><div className="rn-quiz-label"><span>{String(index+1).padStart(2,'0')} · {angleLabels[question.angle]}</span>{question.rating&&<em>{question.rating==='known'?'Biliyorum':question.rating==='partial'?'Kısmen':'Tekrar et'}</em>}</div><h5>{question.prompt}</h5>{question.hint&&<details className="rn-hint"><summary>İpucu</summary><p>{question.hint}</p></details>}<textarea rows={4} value={question.answer} onChange={event=>onChange(current=>({...current,quiz:current.quiz?{...current.quiz,questions:current.quiz.questions.map(item=>item.id===question.id?{...item,answer:event.target.value.slice(0,4000)}:item)}:null}))} placeholder="Kaynaklara bakmadan cevapla…"/>{!show?<button disabled={!question.answer.trim()} onClick={()=>setRevealed(current=>[...current,question.id])}>Anahtar noktaları göster</button>:<div className="rn-key"><strong>Cevabında bunlar var mı?</strong><ul>{question.keyPoints.map(point=><li key={point}>{point}</li>)}</ul><div><button onClick={()=>onChange(current=>({...current,quiz:current.quiz?{...current.quiz,questions:current.quiz.questions.map(item=>item.id===question.id?{...item,rating:'again'}:item)}:null}))}>Tekrar et</button><button onClick={()=>onChange(current=>({...current,quiz:current.quiz?{...current.quiz,questions:current.quiz.questions.map(item=>item.id===question.id?{...item,rating:'partial'}:item)}:null}))}>Kısmen</button><button onClick={()=>onChange(current=>({...current,quiz:current.quiz?{...current.quiz,questions:current.quiz.questions.map(item=>item.id===question.id?{...item,rating:'known'}:item)}:null}))}>Biliyorum</button></div></div>}</article>;})}</div></>}
    </div>}
  </div>;
}
